# Nome do seu fluxo de trabalho (workflow)
name: Playwright Tests

# Gatilhos: Quando a Action deve rodar?
on:
  # Roda quando houver um push para a branch 'main'
  push:
    branches: [ main ]
  # Roda também quando abrirem um Pull Request para a branch 'main'
  pull_request:
    branches: [ main ]

# Trabalhos (jobs) a serem executados
jobs:
  # Nome do nosso job
  test:
    # Em qual sistema operacional o job deve rodar
    runs-on: ubuntu-latest

    # Passos que o job executará em sequência
    steps:
    # 1. Baixa o seu código do repositório para a máquina virtual
    - uses: actions/checkout@v4

    # 2. Instala a versão do Node.js que você precisa
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # 3. Instala as dependências do seu projeto (definidas no package-lock.json)
    - name: Install dependencies
      run: npm ci

    # 4. Instala os navegadores do Playwright (e suas dependências do sistema)
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # 5. Roda os testes do Playwright
    - name: Run Playwright tests
      run: npx playwright test

    # 6. Salva o relatório de testes como um "artefato"
    # Este passo roda SEMPRE, mesmo que os testes falhem, para que você possa ver o relatório do erro.
    - name: Upload report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
